#define NUM_SSIDS 100

const char ssids[] PROGMEM = {
  "How much shade comio el pez?\n"
  "We go after la zona imantada\n"
  "Hiela far away from here\n"
  "White bobo bird migra a Cuba\n"
  "Distance is a nuclear force\n"
  "((((((((((gong))))))))))\n"
  "ttttttrastttttlastttttrejasttt\n"
  //"__/\\______/\\____pocavida_\n"
  //"~~~verso~~que~~flota~~~\n"
  "pain__________________T\n"
  "light suspended en almíbar\n"
  "espumareada\n"
  "parade over fog\n"
  "tercer ojo painted blue\n"
  "meseta in a bottle\n"
  "hasta la Victoria’s Secret.\n"
  "Dios es Amor. ¿Y el Estado?\n"
  "ni pingón ni lira griega\n"
  "hacer que las palabras rajen:\n"
  "duras precisas contundentes\n"
  "flamintocoró dónd tá tu mendó?\n"
  "con q visa lamula n elabismo?\n"
  "Villa JabónKndao? Kf LaLlave!\n"
  "exilia2 i2 qda2 rpatria2: nu2\n"
  "toda Qba la tngo n mi icloud\n"
  "1Grave,Tenso.Pienso:Suave.\n"
  "2Ave,Lienzo.Pienso:Llave.\n"
  "3Pienso:Seco Cabe.\n"
  "4Sabe:Reco-Mienzo.\n"
  "5No me séLa canciónDel minué.\n"
  "Abre la ventana let sounds in\n"
  "Ven acá new best friend\n"
  "Wow bro tú eres romántico\n"
  "My cola es tuKola\n"
  "You win best batido de mamey\n"
  "Máquina+sujeto=sumisión\n"
  "¿T-error como recuerdo?\n"
  "&timeaftertime: enterramientos\n"
  "ensayo@sitemuevesteaplastan\n"
  "yelengranajepasarásobreti.com\n"
  "SeAbreGRITA,SeCierraGRITA\n"
  "MiPadreOdia(NacióDES-NUDO)\n"
  "CalienteDENTROFueraDaigual\n"
  "11:05,14:22,1994,19:15,12:56\n"
  "EnLosBordesDelPrecipicio:Traga\n"
  "From mi ventana I see the flag\n"
  "Carga tu caja through the hall\n"
  "I can't afford casa or country\n"
  "Happy life? Just give me vida\n"
  "Slips of the tongue en mi boca\n"
  "#MiedoAserVistoComoUnSerBovino\n"
  "#LaCerveza:TermómetroDeUnPaís\n"
  "#MuestreSuAmericanidáOrgulloso\n"
  "#COVID-or-not-COVID\n"
  "#AlgoAquíSeDescompone\n"
  "Las sonrisas son Cuban exports\n"
  "Inside us beat tambores Lucumí\n"
  "Ropa vieja can be good clothes\n"
  "Little Cuba: santo por el agua\n"
  "Y nunca, never, será embargada\n"
  "Miami, mami, Miami\n"
  "¡cómo se pone el Yabebirí!\n"
  "¿la isla? un gulag con swing\n"
  "aquí ni vacas ni serial killers\n"
  "unama(n)rchadebibijaguas\n"
  "Las reptiles que te hirieron\n"
  "hermanas de sangre y de frío.\n"
  "Los renacuajos-hijos nadan\n"
  "toman el sol con las manos\n"
  "es el aleteo de los náufragos.\n"
  "Bautizo por caimán\n"
  "Immersa en la incertidumbre\n"
  "Consumiendo mi cabeza completa\n"
  "A pesar de tus dientes afilados\n"
  "Estoy en paz, entregada\n"
  "Lepuedotraeruncupofcoffee?\n"
  "Mucho hielo para tu cuba\n"
  "Y sin embargo I love you\n"
  "Las olas O’ también se rompen\n"
  "Último tip: Nuncajamásnever\n"
  "FLOR IDA A MI A MI\n"
  "Fronteras de sal For Sale\n"
  "Te frizas bróder No me quemes\n"
  "Estrecho Mar Maltrecho\n"
  "El afterclap doblará la bandera\n"
  "Isla flotante alingüística\n"
  "Guardar arena en el almaitis\n"
  "Borré la periferia con marea\n"
  "Living-in-the-hyphen\n"
  "Pies y hiedra rompen paredes\n"
  "¿Home run o carrera a casa?\n"
  "¿Homestead or home instead?\n"
  "¡Qué dos orillas a 90 millas!\n"
  "¡Ay, Cuba! Concepto del dolor.\n"
  "Island of pirates and parrots.\n"
  "Nada bien. Nada, bien.\n"
  "Nuestro mar grows red rosas.\n"
  "My ♥ is in 2 beings, en 2 yos.\n"
  "Si la Patria no tuviera patas…\n"
  "We’re nadas en el mismo lugar."
};